routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\FeedController;
use App\Http\Controllers\MeetupController;
use App\Http\Controllers\MilestoneController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\PatronController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SitemapController;
use App\Http\Controllers\SocialController;
use App\Http\Controllers\StatusController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\TelegramController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WebhookController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth
Auth::routes();
Auth::routes(['verify' => true]);

// Social Auth
Route::get('login/{provider}', [SocialController::class, 'redirect']);
Route::get('login/{provider}/callback', [SocialController::class, 'Callback']);

// 404 Fallback
Route::fallback(function () {
    return response()->view('errors.404', [], 404);
});

// Routes with throttle
Route::group(['middleware' => ['throttle:60,1']], function () {
    // Home
    Route::view('/', 'home.home')->name('home');

    // Explore
    Route::group(['prefix' => 'explore', 'as' => 'explore.'], function () {
        Route::view('', 'explore.explore')->name('explore');
        Route::view('/makers', 'explore.makers')->name('makers');
    });

    // User
    Route::group(['prefix' => '@{username}', 'as' => 'user.'], function () {
        Route::get('', [UserController::class, 'profile'])->name('done');
        Route::get('pending', [UserController::class, 'profile'])->name('pending');
        Route::get('products', [UserController::class, 'profile'])->name('products');
        Route::get('questions', [UserController::class, 'profile'])->name('questions');
        Route::get('answers', [UserController::class, 'profile'])->name('answers');
        Route::get('following', [UserController::class, 'profile'])->name('following');
        Route::get('followers', [UserController::class, 'profile'])->name('followers');
        Route::get('stats', [UserController::class, 'profile'])->name('stats');
    });

    // Settings
    Route::group(['prefix' => 'settings', 'as' => 'user.settings.', 'middleware' => ['auth']], function () {
        Route::get('', [UserController::class, 'profileSettings'])->name('profile');
        Route::get('account', [UserController::class, 'accountSettings'])->name('account');
        Route::get('products', [UserController::class, 'productsSettings'])->name('products');
        Route::get('patron', [UserController::class, 'patronSettings'])->name('patron');
        Route::get('password', [UserController::class, 'passwordSettings'])->name('password');
        Route::get('notifications', [UserController::class, 'notificationsSettings'])->name('notifications');
        Route::get('integrations', [UserController::class, 'integrationsSettings'])->name('integrations');
        Route::get('api', [UserController::class, 'apiSettings'])->name('api');
        Route::get('logs', [UserController::class, 'logsSettings'])->name('logs');
        Route::get('data', [UserController::class, 'dataSettings'])->name('data');
        Route::get('delete', [UserController::class, 'deleteSettings'])->name('delete');
        Route::get('export/account', [UserController::class, 'exportAccount'])->name('export.account');
        Route::get('export/logs', [UserController::class, 'exportLogs'])->name('export.logs');
    });

    // Notifications
    Route::group(['prefix' => 'notifications', 'as' => 'notifications.', 'middleware' => ['auth']], function () {
        Route::view('', 'notifications.unread')->name('unread');
        Route::view('all', 'notifications.all')->name('all');
    });

    // Suspended
    Route::view('suspended', 'auth.suspended')->name('suspended');

    // Avatar
    Route::get('avatar/{username}.png', [UserController::class, 'avatar'])->name('avatar');

    // Webhooks
    Route::group(['prefix' => 'webhook'], function () {
        Route::post('web/{token}', [WebhookController::class, 'web']);
        Route::post('version/{appkey}', [WebhookController::class, 'newVersion']);
    });

    // Product
    Route::group(['prefix' => 'product/{slug}', 'as' => 'product.'], function () {
        Route::get('', [ProductController::class, 'profile'])->name('done');
        Route::get('pending', [ProductController::class, 'profile'])->name('pending');
        Route::get('updates', [ProductController::class, 'profile'])->name('updates');
        Route::get('subscribers', [ProductController::class, 'profile'])->name('subscribers');
    });

    // Products
    Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
        Route::get('', [ProductController::class, 'newest'])->name('newest');
        Route::get('launched', [ProductController::class, 'launched'])->name('launched');
    });

    // Question
    Route::group(['prefix' => 'question', 'as' => 'question.'], function () {
        Route::get('{id}', [QuestionController::class, 'question'])->name('question');
    });

    // Questions
    Route::group(['prefix' => 'questions', 'as' => 'questions.'], function () {
        Route::get('', [QuestionController::class, 'newest'])->name('newest');
        Route::get('unanswered', [QuestionController::class, 'unanswered'])->name('unanswered');
        Route::get('popular', [QuestionController::class, 'popular'])->name('popular');
    });

    // Milestone
    Route::group(['prefix' => 'milestones', 'as' => 'milestones.'], function () {
        Route::get('', [MilestoneController::class, 'opened'])->name('opened');
        Route::get('closed', [MilestoneController::class, 'closed'])->name('closed');
        Route::get('{id}', [MilestoneController::class, 'milestone'])->name('milestone');
    });

    // Search
    Route::group(['prefix' => 'search', 'as' => 'search.'], function () {
        Route::get('', [SearchController::class, 'search'])->name('home');
        Route::get('tasks', [SearchController::class, 'tasks'])->name('tasks');
        Route::get('comments', [SearchController::class, 'comments'])->name('comments');
        Route::get('questions', [SearchController::class, 'questions'])->name('questions');
        Route::get('answers', [SearchController::class, 'answers'])->name('answers');
        Route::get('products', [SearchController::class, 'products'])->name('products');
        Route::get('users', [SearchController::class, 'users'])->name('users');
    });

    // Admin
    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['staff']], function () {
        Route::view('users', 'admin.users')->middleware('password.confirm')->name('users');
        Route::view('tasks', 'admin.tasks')->middleware('password.confirm')->name('tasks');
        Route::view('activities', 'admin.activities')->middleware('password.confirm')->name('activities');
        Route::view('products', 'admin.products')->middleware('password.confirm')->name('products');
        Route::get('adminbar', [AdminController::class, 'toggle'])->name('adminbar');
    });

    // Patron
    Route::group(['prefix' => 'patron', 'as' => 'patron.'], function () {
        Route::view('', 'pages.patron')->name('home');
    });

    // Paddle Integration
    Route::post('paddle/webhook', [PatronController::class, 'handleWebhook'])->name('paddle.webhook');

    // Dark mode
    Route::get('darkmode', [UserController::class, 'darkMode'])->name('darkmode')->middleware('patron');

    // Single Task and comment
    Route::group(['prefix' => 'task'], function () {
        Route::get('{id}', [TaskController::class, 'task'])->name('task');
        Route::get('{id}/{comment_id}', [TaskController::class, 'comment'])->name('comment');
    });

    // Zen mode tasks
    Route::view('tasks', 'tasks.tasks')->name('tasks')->middleware('auth');

    // Pages
    Route::view('about', 'pages.about')->name('about');
    Route::view('terms', 'pages.terms')->name('terms');
    Route::view('privacy', 'pages.privacy')->name('privacy');
    Route::view('security', 'pages.security')->name('security');
    Route::view('sponsors', 'pages.sponsors')->name('sponsors');
    Route::view('contact', 'pages.contact')->name('contact');
    Route::view('reputation', 'pages.reputation')->name('reputation')->middleware('auth');
    Route::view('open', 'pages.open')->name('open');
    Route::get('deals', [PagesController::class, 'deals'])->name('deals');

    // Meetups
    Route::group(['prefix' => 'meetups', 'as' => 'meetups.'], function () {
        Route::get('/', [MeetupController::class, 'meetups'])->name('home')->middleware('staff');
        Route::get('/rsvpd', [MeetupController::class, 'rsvpd'])->name('rsvpd')->middleware('staff');
        Route::get('/finished', [MeetupController::class, 'finished'])->name('finished')->middleware('staff');
    });

    // https://web.dev/change-password-url
    Route::get('.well-known/change-password', function () {
        return redirect()->route('user.settings.password');
    });

    // Sitemaps
    Route::get('sitemap_users.txt', [SitemapController::class, 'users']);
    Route::get('sitemap_products.txt', [SitemapController::class, 'products']);
    Route::get('sitemap_questions.txt', [SitemapController::class, 'questions']);
    Route::get('sitemap_tasks.txt', [SitemapController::class, 'tasks']);
    Route::get('sitemap_comments.txt', [SitemapController::class, 'comments']);
    Route::view('sitemap_urls.txt', 'seo.sitemap_urls');

    // Status

app/Http/Livewire/Admin/Activities.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;
use Livewire\WithPagination;
use Spatie\Activitylog\Models\Activity;

class Activities extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    public $readyToLoad = false;

    public function loadActivities()
    {
        $this->readyToLoad = true;
    }

    public function getActivities()
    {
        return Activity::latest()->paginate('50');
    }

    public function render()
    {
        return view('livewire.admin.activities', [
            'activities' => $this->readyToLoad ? $this->getActivities() : [],
            'count' => number_format(Activity::count('id')),
        ]);
    }
}

app/Http/Livewire/Admin/Adminbar.php
<?php

namespace App\Http\Livewire\Admin;

use App\Jobs\Clean;
use App\Jobs\Deploy;
use App\Models\Answer;
use App\Models\Comment;
use App\Models\Product;
use App\Models\Question;
use App\Models\Task;
use App\Models\User;
use App\Models\Webhook;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Queue;
use Livewire\Component;
use Spatie\Activitylog\Models\Activity;

class Adminbar extends Component
{
    protected $listeners = [
        'refreshStats' => 'render',
    ];

    public function refreshStats()
    {
        loggy(request()->ip(), 'Admin', auth()->user(), 'Refreshed Adminbar Status');

        $this->emitSelf('refreshStats');
    }

    public function clean()
    {
        Clean::dispatch()->delay(now()->addSeconds(10));
        loggy(request()->ip(), 'Admin', auth()->user(), 'Cleaned the Application');

        return $this->alert('success', 'Cleaning process has been initiated successfully 🧼');
    }

    public function deploy()
    {
        if (auth()->id() === 1) {
            Deploy::dispatch(auth()->user(), request()->ip());
            loggy(request()->ip(), 'Admin', auth()->user(), 'Deployed the Application');

            return $this->alert('success', 'Deployment process has been initiated successfully 🚀');
        } else {
            return $this->alert('error', 'Permission denied!');
        }
    }

    public function render()
    {
        $branch = git('rev-parse --abbrev-ref HEAD') ?: 'main';
        $commit = git('rev-parse --short HEAD') ?: '0000000';

        // DB Details
        $tasks = Task::count('id');
        $users = User::count('id');
        $products = Product::count('id');
        $reputations = User::sum('reputation');
        $questions = Question::count('id');
        $answers = Answer::count('id');
        $comments = Comment::count('id');
        $webhooks = Webhook::count('id');
        $notifications = DB::table('notifications')->count('id');
        $logs = Activity::count('id');
        $interactions = DB::table('interactions')->count();
        $praises = DB::table('interactions')->whereRelation('like')->count();
        $jobs = Queue::size();
        $cache = Cache::getStore()->getMemcached()->getAllKeys() ?: [];

        return view('livewire.admin.adminbar', [
            'branchname' => $branch,
            'headHASH' => $commit,
            'tasks' => number_format($tasks),
            'users' => number_format($users),
            'products' => number_format($products),
            'reputations' => number_format($reputations),
            'questions' => number_format($questions),
            'answers' => number_format($answers),
            'comments' => number_format($comments),
            'notifications' => number_format($notifications),
            'interactions' => number_format($interactions),
            'logs' => number_format($logs),
            'praises' => number_format($praises),
            'jobs' => number_format($jobs),
            'cache' => number_format(count($cache)),
            'webhooks' => number_format($webhooks),
        ]);
    }
}

app/Http/Livewire/Admin/Products.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\Product;
use Livewire\Component;
use Livewire\WithPagination;

class Products extends Component
{
    use WithPagination;

    protected string $paginationTheme = 'bootstrap';

    public bool $readyToLoad = false;

    public function loadProducts()
    {
        $this->readyToLoad = true;
    }

    public function getProducts()
    {
        return Product::with('owner')
            ->withCount(['members', 'tasks', 'product_update'])
            ->latest()->paginate(50);
    }

    public function render()
    {
        return view('livewire.admin.products', [
            'products' => $this->readyToLoad ? $this->getProducts() : [],
            'count'    => $this->readyToLoad ? Product::count('id') : [],
        ]);
    }
}

app/Http/Livewire/Admin/Tasks.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\Task;
use Livewire\Component;
use Livewire\WithPagination;

class Tasks extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    public $readyToLoad = false;

    public function loadTasks()
    {
        $this->readyToLoad = true;
    }

    public function getTasks()
    {
        return Task::latest()->paginate(50);
    }

    public function render()
    {
        return view('livewire.admin.tasks', [
            'tasks' => $this->readyToLoad ? $this->getTasks() : [],
            'count' => $this->readyToLoad ? Task::count('id') : [],
        ]);
    }
}

app/Http/Livewire/Admin/Users.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\User;
use Livewire\Component;
use Livewire\WithPagination;

class Users extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    public $readyToLoad = false;

    public function loadUsers()
    {
        $this->readyToLoad = true;
    }

    public function getUsers()
    {
        return User::latest('last_active')->paginate(50);
    }

    public function render()
    {
        return view('livewire.admin.users', [
            'users' => $this->readyToLoad ? $this->getUsers() : [],
            'count' => $this->readyToLoad ? User::count('id') : [],
        ]);
    }
}

app/Http/Livewire/Answer/Answers.php
<?php

namespace App\Http\Livewire\Answer;

use App\Models\Answer;
use App\Models\Question;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Collection;
use Livewire\Component;

class Answers extends Component
{
    public $listeners = [
        'answerAdded' => 'render',
        'answerDeleted' => 'render',
    ];

    public Question $question;
    public $page;
    public $perPage;
    public $readyToLoad = false;

    public function mount($question, $page, $perPage)
    {
        $this->question = $question;
        $this->page = $page ? $page : 1;
        $this->perPage = $perPage ? $perPage : 1;
    }

    public function loadAnswers()
    {
        $this->readyToLoad = true;
    }

    public function getAnswers()
    {
        return Answer::where('question_id', $this->question->id)
            ->whereHas('user', function ($q) {
                $q->where([
                    ['isFlagged', false],
                ]);
            })
            ->orderBy('created_at', 'DESC')
            ->get();
    }

    public function paginate($items, $options = [])
    {
        $page = $this->page ?: (Paginator::resolveCurrentPage() ?: 1);
        $items = $items instanceof Collection ? $items : Collection::make($items);

        return new LengthAwarePaginator($items->forPage($page, $this->perPage), $items->count(), $this->perPage, $page, $options);
    }

    public function render()
    {
        return view('livewire.answer.answers', [
            'answers' => $this->readyToLoad ? $this->paginate($this->getAnswers()) : [],
            'page' => $this->page,
        ]);
    }
}

resources/views/livewire/admin/activities.blade.php
<div class="card" wire:init="loadActivities" wire:poll>
    <div class="card-header h6 pt-3 pb-3">
        <div class="h5">Activities</div>
        <span class="fw-bold">{{ $readyToLoad ? $count : '···' }}</span>
        total activities
    </div>
    <div class="table-responsive">
        @if ($readyToLoad)
        <ul class="list-group list-group-flush">
            @foreach ($activities as $activity)
            <x-user-activity :activity="$activity" />
            @endforeach
        </ul>
        @endif
        @if (!$readyToLoad)
        <div class="card-body text-center mt-3">
            <div class="spinner-border taskord-spinner text-secondary mb-3" role="status"></div>
            <div class="h6">
                Loading activities...
            </div>
        </div>
        @endif
    </div>
    {{ $readyToLoad ? $activities->links() : '' }}
</div>

resources/views/livewire/admin/products.blade.php
<div class="card" wire:init="loadProducts">
    <div class="card-header h6 pt-3 pb-3">
        <div class="h5">Products</div>
        <span class="fw-bold">{{ $readyToLoad ? $count : '···' }}</span>
        total products
    </div>
    <div class="table-responsive">
        @if ($readyToLoad)
        <table class="table text-dark">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Product</th>
                    <th scope="col">Owner</th>
                    <th scope="col">Members</th>
                    <th scope="col">Tasks</th>
                    <th scope="col">Updates</th>
                    <th scope="col">Launched</th>
                    <th scope="col">Launched At</th>
                    <th scope="col">Created At</th>
                    <th scope="col">Updated At</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($products as $product)
                <tr>
                    <th>{{ $product->id }}</th>
                    <td>
                        <a href="{{ route('product.done', ['slug' => $product->slug]) }}">
                            {{ $product->name }}
                        </a>
                    </td>
                    <td>
                        <a href="{{ route('user.done', ['username' => $product->owner->username]) }}" target="_blank">
                            {{ '@'.$product->owner->username }}
                        </a>
                    </td>
                    <td>
                        {{ $product->members_count }}
                    </td>
                    <td>
                        {{ $product->tasks_count }}
                    </td>
                    <td>
                        {{ $product->product_update_count }}
                    </td>
                    <td>
                        @if ($product->launched)
                        ✅
                        @else
                        ❌
                        @endif
                    </td>
                    <td>
                        @if ($product->launched_at)
                            <time datetime="{{ $product->launched_at->format('Y-m-d') }}">
                                {{ $product->launched_at->format('M d, Y') }}
                            </time>
                        @else
                            TBD
                        @endif
                    </td>
                    <td>
                        <time datetime="{{ $product->created_at->format('Y-m-d') }}">
                            {{ $product->created_at->format('M d, Y') }}
                        </time>
                    </td>
                    <td>
                        <time datetime="{{ $product->updated_at->format('Y-m-d') }}">
                            {{ $product->updated_at->format('M d, Y') }}
                        </time>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        @endif
        @if (!$readyToLoad)
        <div class="card-body text-center mt-3">
            <div class="spinner-border taskord-spinner text-secondary mb-3" role="status"></div>
            <div class="h6">
                Loading Products...
            </div>
        </div>
        @endif
    </div>
    {{ $readyToLoad ? $products->links() : '' }}
</div>

resources/views/livewire/admin/tasks.blade.php
<div class="card" wire:init="loadTasks">
    <div class="card-header h6 pt-3 pb-3">
        <div class="h5">Tasks</div>
        <span class="fw-bold">{{ $readyToLoad ? $count : '···' }}</span>
        total tasks
    </div>
    <div class="table-responsive">
        @if ($readyToLoad)
        <table class="table text-dark">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Username</th>
                    <th scope="col">Status</th>
                    <th scope="col">Task</th>
                    <th scope="col">Updated</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($tasks as $task)
                <tr>
                    <th>{{ $task->id }}</th>
                    <td>
                        <a href="{{ route('user.done', ['username' => $task->user->username]) }}" target="_blank">
                            {{ '@'.$task->user->username }}
                        </a>
                    </td>
                    <td>
                        @if ($task->done)
                        ✅
                        @else
                        ⌛
                        @endif
                    </td>
                    <td>
                        <a href="{{ route('task', ['id' => $task->id]) }}">
                            {{ Str::limit($task->task, '100') }}
                        </a>
                        @if ($task->hidden)
                        <span title="Flagged">🤢</span>
                        @endif
                    </td>
                    <td>
                        <span title="{{ $task->updated_at->format('M d, Y g:i A') }}">
                            {{ $task->updated_at->format('M d, Y') }}
                        </span>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        @endif
        @if (!$readyToLoad)
        <div class="card-body text-center mt-3">
            <div class="spinner-border taskord-spinner text-secondary mb-3" role="status"></div>
            <div class="h6">
                Loading Tasks...
            </div>
        </div>
        @endif
    </div>
    {{ $readyToLoad ? $tasks->links() : '' }}
</div>