routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\FeedController;
use App\Http\Controllers\MeetupController;
use App\Http\Controllers\MilestoneController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\PatronController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SitemapController;
use App\Http\Controllers\SocialController;
use App\Http\Controllers\StatusController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\TelegramController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WebhookController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth
Auth::routes();
Auth::routes(['verify' => true]);

// Social Auth
Route::get('login/{provider}', [SocialController::class, 'redirect']);
Route::get('login/{provider}/callback', [SocialController::class, 'Callback']);

// 404 Fallback
Route::fallback(function () {
    return response()->view('errors.404', [], 404);
});

// Routes with throttle
Route::group(['middleware' => ['throttle:60,1']], function () {
    // Home
    Route::view('/', 'home.home')->name('home');

    // Explore
    Route::group(['prefix' => 'explore', 'as' => 'explore.'], function () {
        Route::view('', 'explore.explore')->name('explore');
        Route::view('/makers', 'explore.makers')->name('makers');
    });

    // User
    Route::group(['prefix' => '@{username}', 'as' => 'user.'], function () {
        Route::get('', [UserController::class, 'profile'])->name('done');
        Route::get('pending', [UserController::class, 'profile'])->name('pending');
        Route::get('products', [UserController::class, 'profile'])->name('products');
        Route::get('questions', [UserController::class, 'profile'])->name('questions');
        Route::get('answers', [UserController::class, 'profile'])->name('answers');
        Route::get('following', [UserController::class, 'profile'])->name('following');
        Route::get('followers', [UserController::class, 'profile'])->name('followers');
        Route::get('stats', [UserController::class, 'profile'])->name('stats');
    });

    // Settings
    Route::group(['prefix' => 'settings', 'as' => 'user.settings.', 'middleware' => ['auth']], function () {
        Route::get('', [UserController::class, 'profileSettings'])->name('profile');
        Route::get('account', [UserController::class, 'accountSettings'])->name('account');
        Route::get('products', [UserController::class, 'productsSettings'])->name('products');
        Route::get('patron', [UserController::class, 'patronSettings'])->name('patron');
        Route::get('password', [UserController::class, 'passwordSettings'])->name('password');
        Route::get('notifications', [UserController::class, 'notificationsSettings'])->name('notifications');
        Route::get('integrations', [UserController::class, 'integrationsSettings'])->name('integrations');
        Route::get('api', [UserController::class, 'apiSettings'])->name('api');
        Route::get('logs', [UserController::class, 'logsSettings'])->name('logs');
        Route::get('data', [UserController::class, 'dataSettings'])->name('data');
        Route::get('delete', [UserController::class, 'deleteSettings'])->name('delete');
        Route::get('export/account', [UserController::class, 'exportAccount'])->name('export.account');
        Route::get('export/logs', [UserController::class, 'exportLogs'])->name('export.logs');
    });

    // Notifications
    Route::group(['prefix' => 'notifications', 'as' => 'notifications.', 'middleware' => ['auth']], function () {
        Route::view('', 'notifications.unread')->name('unread');
        Route::view('all', 'notifications.all')->name('all');
    });

    // Suspended
    Route::view('suspended', 'auth.suspended')->name('suspended');

    // Avatar
    Route::get('avatar/{username}.png', [UserController::class, 'avatar'])->name('avatar');

    // Webhooks
    Route::group(['prefix' => 'webhook'], function () {
        Route::post('web/{token}', [WebhookController::class, 'web']);
        Route::post('version/{appkey}', [WebhookController::class, 'newVersion']);
    });

    // Product
    Route::group(['prefix' => 'product/{slug}', 'as' => 'product.'], function () {
        Route::get('', [ProductController::class, 'profile'])->name('done');
        Route::get('pending', [ProductController::class, 'profile'])->name('pending');
        Route::get('updates', [ProductController::class, 'profile'])->name('updates');
        Route::get('subscribers', [ProductController::class, 'profile'])->name('subscribers');
    });

    // Products
    Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
        Route::get('', [ProductController::class, 'newest'])->name('newest');
        Route::get('launched', [ProductController::class, 'launched'])->name('launched');
    });

    // Question
    Route::group(['prefix' => 'question', 'as' => 'question.'], function () {
        Route::get('{id}', [QuestionController::class, 'question'])->name('question');
    });

    // Questions
    Route::group(['prefix' => 'questions', 'as' => 'questions.'], function () {
        Route::get('', [QuestionController::class, 'newest'])->name('newest');
        Route::get('unanswered', [QuestionController::class, 'unanswered'])->name('unanswered');
        Route::get('popular', [QuestionController::class, 'popular'])->name('popular');
    });

    // Milestone
    Route::group(['prefix' => 'milestones', 'as' => 'milestones.'], function () {
        Route::get('', [MilestoneController::class, 'opened'])->name('opened');
        Route::get('closed', [MilestoneController::class, 'closed'])->name('closed');
        Route::get('{id}', [MilestoneController::class, 'milestone'])->name('milestone');
    });

    // Search
    Route::group(['prefix' => 'search', 'as' => 'search.'], function () {
        Route::get('', [SearchController::class, 'search'])->name('home');
        Route::get('tasks', [SearchController::class, 'tasks'])->name('tasks');
        Route::get('comments', [SearchController::class, 'comments'])->name('comments');
        Route::get('questions', [SearchController::class, 'questions'])->name('questions');
        Route::get('answers', [SearchController::class, 'answers'])->name('answers');
        Route::get('products', [SearchController::class, 'products'])->name('products');
        Route::get('users', [SearchController::class, 'users'])->name('users');
    });

    // Admin
    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['staff']], function () {
        Route::view('users', 'admin.users')->middleware('password.confirm')->name('users');
        Route::view('tasks', 'admin.tasks')->middleware('password.confirm')->name('tasks');
        Route::view('activities', 'admin.activities')->middleware('password.confirm')->name('activities');
        Route::view('products', 'admin.products')->middleware('password.confirm')->name('products');
        Route::get('adminbar', [AdminController::class, 'toggle'])->name('adminbar');
    });

    // Patron
    Route::group(['prefix' => 'patron', 'as' => 'patron.'], function () {
        Route::view('', 'pages.patron')->name('home');
    });

    // Paddle Integration
    Route::post('paddle/webhook', [PatronController::class, 'handleWebhook'])->name('paddle.webhook');

    // Dark mode
    Route::get('darkmode', [UserController::class, 'darkMode'])->name('darkmode')->middleware('patron');

    // Single Task and comment
    Route::group(['prefix' => 'task'], function () {
        Route::get('{id}', [TaskController::class, 'task'])->name('task');
        Route::get('{id}/{comment_id}', [TaskController::class, 'comment'])->name('comment');
    });

    // Zen mode tasks
    Route::view('tasks', 'tasks.tasks')->name('tasks')->middleware('auth');

    // Pages
    Route::view('about', 'pages.about')->name('about');
    Route::view('terms', 'pages.terms')->name('terms');
    Route::view('privacy', 'pages.privacy')->name('privacy');
    Route::view('security', 'pages.security')->name('security');
    Route::view('sponsors', 'pages.sponsors')->name('sponsors');
    Route::view('contact', 'pages.contact')->name('contact');
    Route::view('reputation', 'pages.reputation')->name('reputation')->middleware('auth');
    Route::view('open', 'pages.open')->name('open');
    Route::get('deals', [PagesController::class, 'deals'])->name('deals');

    // Meetups
    Route::group(['prefix' => 'meetups', 'as' => 'meetups.'], function () {
        Route::get('/', [MeetupController::class, 'meetups'])->name('home')->middleware('staff');
        Route::get('/rsvpd', [MeetupController::class, 'rsvpd'])->name('rsvpd')->middleware('staff');
        Route::get('/finished', [MeetupController::class, 'finished'])->name('finished')->middleware('staff');
    });

    // https://web.dev/change-password-url
    Route::get('.well-known/change-password', function () {
        return redirect()->route('user.settings.password');
    });

    // Sitemaps
    Route::get('sitemap_users.txt', [SitemapController::class, 'users']);
    Route::get('sitemap_products.txt', [SitemapController::class, 'products']);
    Route::get('sitemap_questions.txt', [SitemapController::class, 'questions']);
    Route::get('sitemap_tasks.txt', [SitemapController::class, 'tasks']);
    Route::get('sitemap_comments.txt', [SitemapController::class, 'comments']);
    Route::view('sitemap_urls.txt', 'seo.sitemap_urls');

    // Status

app/Models/Meetup.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Multicaret\Acquaintances\Traits\CanBeSubscribed;
use Rennokki\QueryCache\Traits\QueryCacheable;

class Meetup extends Model
{
    use CanBeSubscribed;
    use QueryCacheable;
    use HasFactory;

    public $cacheFor = 3600;
    public $cacheTags = ['meetups'];
    public $cachePrefix = 'meetups_';
    protected static $flushCacheOnUpdate = true;
    protected $fillable = [
        'user_id',
        'name',
        'slug',
        'tagline',
        'description',
        'location',
        'cover',
        'date',
        'hidden',
    ];

    public function user()
    {
        return $this->belongsTo(\App\Models\User::class, 'user_id');
    }
}

app/Http/Controllers/MeetupController.php
<?php

namespace App\Http\Controllers;

use App\Models\Meetup;

class MeetupController extends Controller
{
    public function meetups()
    {
        $meetups = Meetup::where('date', '>=', date('Y-m-d'))
            ->orderBy('date')
            ->paginate(12);

        return view('meetups.meetups', [
            'meetups' => $meetups,
        ]);
    }

    public function finished()
    {
        $meetups = Meetup::where('date', '<=', date('Y-m-d'))
            ->latest()
            ->paginate(12);

        return view('meetups.finished', [
            'meetups' => $meetups,
        ]);
    }

    public function rsvpd()
    {
        $meetups = auth()->user()->subscriptions(Meetup::class)
            ->orderBy('date')
            ->get();

        return view('meetups.rsvpd', [
            'meetups' => $meetups,
        ]);
    }
}

app/Http/Livewire/Meetup/NewMeetup.php
<?php

namespace App\Http\Livewire\Meetup;

use App\Models\Meetup;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Intervention\Image\Facades\Image;
use Livewire\Component;
use Livewire\WithFileUploads;

class NewMeetup extends Component
{
    use WithFileUploads;

    public $name;
    public $slug;
    public $cover;
    public $tagline;
    public $description;
    public $location;
    public $date;

    public function updatedCover()
    {
        if (Auth::check()) {
            $this->validate([
                'cover' => 'nullable|mimes:jpeg,jpg,png,gif|max:1024',
            ]);
        } else {
            return $this->alert('error', 'Forbidden!');
        }
    }

    public function submit()
    {
        if (Auth::check()) {
            $this->validate([
                'name' => 'required|max:30',
                'slug' => 'required|min:3|max:20|unique:meetups|alpha_dash',
                'tagline' => 'required|max:160',
                'description' => 'nullable|max:50000',
                'location' => 'nullable|max:50',
                'date' => 'required|date',
                'cover' => 'nullable|mimes:jpeg,jpg,png,gif|max:1024',
            ]);

            if (! auth()->user()->hasVerifiedEmail()) {
                return $this->alert('warning', 'Your email is not verified!');
            }

            if (auth()->user()->isFlagged) {
                return $this->alert('error', 'Your account is flagged!');
            }

            if ($this->cover) {
                $img = Image::make($this->cover)
                        ->fit(1500)
                        ->crop(1500, 500)
                        ->encode('webp', 100);
                $imageName = Str::random(32).'.webp';
                Storage::disk('public')->put('meetup-cover/'.$imageName, (string) $img);
                $url = config('app.url').'/storage/meetup-cover/'.$imageName;
            } else {
                $url = 'https://avatar.tobi.sh/'.md5($this->slug).'.svg?text=📦';
            }

            $meetup = Meetup::create([
                'user_id' =>  auth()->user()->id,
                'name' => $this->name,
                'slug' => $this->slug,
                'cover' => $url,
                'tagline' => $this->tagline,
                'description' => $this->description,
                'location' => $this->location,
                'date' => $this->date,
            ]);
            auth()->user()->touch();

            $this->flash('success', 'Meetup has been created!');

            return redirect()->route('meetups.home');
        } else {
            $this->alert('error', 'Forbidden!');
        }
    }
}

app/Http/Livewire/Meetup/Rsvp.php
<?php

namespace App\Http\Livewire\Meetup;

use App\Models\Meetup;
use GrahamCampbell\Throttle\Facades\Throttle;
use Helper;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Request;
use Livewire\Component;

class Rsvp extends Component
{
    public Meetup $meetup;

    public function mount($meetup)
    {
        $this->meetup = $meetup;
    }

    public function toggleRSVP()
    {
        $throttler = Throttle::get(Request::instance(), 20, 5);
        $throttler->hit();
        if (count($throttler) > 30) {
            Helper::flagAccount(auth()->user());
        }
        if (! $throttler->check()) {
            loggy(request()->ip(), 'Throttle', auth()->user(), 'Rate limited while toggling the RSVP');

            return $this->alert('error', 'Your are rate limited, try again later!');
        }

        if (Auth::check()) {
            if (! auth()->user()->hasVerifiedEmail()) {
                return $this->alert('warning', 'Your email is not verified!');
            }
            if (auth()->user()->isFlagged) {
                return $this->alert('error', 'Your account is flagged!');
            }
            if (auth()->user()->id === $this->meetup->user_id) {
                return $this->alert('warning', 'You can\'t RSVP your own meetup!');
            } else {
                auth()->user()->toggleSubscribe($this->meetup);
                $this->meetup->refresh();
                auth()->user()->touch();
            }
        } else {
            return $this->alert('error', 'Forbidden!');
        }
    }
}

app/Http/Livewire/Meetup/SingleMeetup.php
<?php

namespace App\Http\Livewire\Meetup;

use App\Models\Meetup;
use Livewire\Component;

class SingleMeetup extends Component
{
    public Meetup $meetup;

    public function mount($meetup)
    {
        $this->meetup = $meetup;
    }
}

resources/views/meetups/finished.blade.php
@extends('layouts.app')

@section('pageTitle', 'Meetups - RSVPd ·')
@section('title', 'Meetups - RSVPd ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
    <div class="container-md">
        <div class="card">
            @include('meetups.header')
            <div class="card-body">
                @if (count($meetups) === 0)
                <div class="card-body text-center mt-3 mb-3">
                    <x-heroicon-o-user-group class="heroicon-4x text-primary mb-2" />
                    <div class="h4">
                        No finished meetups found
                    </div>
                </div>
                @endif
                <div class="container-fluid">
                    <div class="row">
                        @foreach ($meetups as $meetup)
                            @livewire('meetup.single-meetup', ['meetup' => $meetup])
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/meetups/header.blade.php
<div class="card-header pt-3 pb-3">
    <div class="d-flex justify-content-between align-items-center">
        <div>
            <div class="h5">Meetups <x-staffship background="light" /></div>
            <div>Meet and greet.</div>
        </div>
        <div>
            <a href="{{ route('meetups.rsvpd') }}" class="btn btn-outline-success">
                RSVPd
            </a>
            <a href="{{ route('meetups.finished') }}" class="btn btn-outline-primary">
                Finished
            </a>
            @auth
                <button class="btn btn-success text-white" data-bs-toggle="modal" data-bs-target="#newMeetupModal">
                    <x-heroicon-o-plus class="heroicon" />
                    New Meetup
                </button>
                @livewire('meetup.new-meetup')
            @endauth
        </div>
    </div>
</div>

resources/views/meetups/meetups.blade.php
@extends('layouts.app')

@section('pageTitle', 'Meetups ·')
@section('title', 'Meetups ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
    <div class="container-md">
        <div class="card">
            @include('meetups.header')
            <div class="card-body">
                @if (count($meetups) === 0)
                <div class="card-body text-center mt-3 mb-3">
                    <x-heroicon-o-user-group class="heroicon-4x text-primary mb-2" />
                    <div class="h4">
                        No meetups found
                    </div>
                </div>
                @endif
                <div class="container-fluid">
                    <div class="row">
                        @foreach ($meetups as $meetup)
                            @livewire('meetup.single-meetup', ['meetup' => $meetup])
                        @endforeach
                        {{ $meetups->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/meetups/rsvpd.blade.php
@extends('layouts.app')

@section('pageTitle', 'Meetups - RSVPd ·')
@section('title', 'Meetups - RSVPd ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
    <div class="container-md">
        <div class="card">
            @include('meetups.header')
            <div class="card-body">
                @if (count($meetups) === 0)
                <div class="card-body text-center mt-3 mb-3">
                    <x-heroicon-o-user-group class="heroicon-4x text-primary mb-2" />
                    <div class="h4">
                        No RSVPd meetups found
                    </div>
                </div>
                @endif
                <div class="container-fluid">
                    <div class="row">
                        @foreach ($meetups as $meetup)
                            @livewire('meetup.single-meetup', ['meetup' => $meetup])
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection