routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\FeedController;
use App\Http\Controllers\MeetupController;
use App\Http\Controllers\MilestoneController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\PatronController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SitemapController;
use App\Http\Controllers\SocialController;
use App\Http\Controllers\StatusController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\TelegramController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WebhookController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth
Auth::routes();
Auth::routes(['verify' => true]);

// Social Auth
Route::get('login/{provider}', [SocialController::class, 'redirect']);
Route::get('login/{provider}/callback', [SocialController::class, 'Callback']);

// 404 Fallback
Route::fallback(function () {
    return response()->view('errors.404', [], 404);
});

// Routes with throttle
Route::group(['middleware' => ['throttle:60,1']], function () {
    // Home
    Route::view('/', 'home.home')->name('home');

    // Explore
    Route::group(['prefix' => 'explore', 'as' => 'explore.'], function () {
        Route::view('', 'explore.explore')->name('explore');
        Route::view('/makers', 'explore.makers')->name('makers');
    });

    // User
    Route::group(['prefix' => '@{username}', 'as' => 'user.'], function () {
        Route::get('', [UserController::class, 'profile'])->name('done');
        Route::get('pending', [UserController::class, 'profile'])->name('pending');
        Route::get('products', [UserController::class, 'profile'])->name('products');
        Route::get('questions', [UserController::class, 'profile'])->name('questions');
        Route::get('answers', [UserController::class, 'profile'])->name('answers');
        Route::get('following', [UserController::class, 'profile'])->name('following');
        Route::get('followers', [UserController::class, 'profile'])->name('followers');
        Route::get('stats', [UserController::class, 'profile'])->name('stats');
    });

    // Settings
    Route::group(['prefix' => 'settings', 'as' => 'user.settings.', 'middleware' => ['auth']], function () {
        Route::get('', [UserController::class, 'profileSettings'])->name('profile');
        Route::get('account', [UserController::class, 'accountSettings'])->name('account');
        Route::get('products', [UserController::class, 'productsSettings'])->name('products');
        Route::get('patron', [UserController::class, 'patronSettings'])->name('patron');
        Route::get('password', [UserController::class, 'passwordSettings'])->name('password');
        Route::get('notifications', [UserController::class, 'notificationsSettings'])->name('notifications');
        Route::get('integrations', [UserController::class, 'integrationsSettings'])->name('integrations');
        Route::get('api', [UserController::class, 'apiSettings'])->name('api');
        Route::get('logs', [UserController::class, 'logsSettings'])->name('logs');
        Route::get('data', [UserController::class, 'dataSettings'])->name('data');
        Route::get('delete', [UserController::class, 'deleteSettings'])->name('delete');
        Route::get('export/account', [UserController::class, 'exportAccount'])->name('export.account');
        Route::get('export/logs', [UserController::class, 'exportLogs'])->name('export.logs');
    });

    // Notifications
    Route::group(['prefix' => 'notifications', 'as' => 'notifications.', 'middleware' => ['auth']], function () {
        Route::view('', 'notifications.unread')->name('unread');
        Route::view('all', 'notifications.all')->name('all');
    });

    // Suspended
    Route::view('suspended', 'auth.suspended')->name('suspended');

    // Avatar
    Route::get('avatar/{username}.png', [UserController::class, 'avatar'])->name('avatar');

    // Webhooks
    Route::group(['prefix' => 'webhook'], function () {
        Route::post('web/{token}', [WebhookController::class, 'web']);
        Route::post('version/{appkey}', [WebhookController::class, 'newVersion']);
    });

    // Product
    Route::group(['prefix' => 'product/{slug}', 'as' => 'product.'], function () {
        Route::get('', [ProductController::class, 'profile'])->name('done');
        Route::get('pending', [ProductController::class, 'profile'])->name('pending');
        Route::get('updates', [ProductController::class, 'profile'])->name('updates');
        Route::get('subscribers', [ProductController::class, 'profile'])->name('subscribers');
    });

    // Products
    Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
        Route::get('', [ProductController::class, 'newest'])->name('newest');
        Route::get('launched', [ProductController::class, 'launched'])->name('launched');
    });

    // Question
    Route::group(['prefix' => 'question', 'as' => 'question.'], function () {
        Route::get('{id}', [QuestionController::class, 'question'])->name('question');
    });

    // Questions
    Route::group(['prefix' => 'questions', 'as' => 'questions.'], function () {
        Route::get('', [QuestionController::class, 'newest'])->name('newest');
        Route::get('unanswered', [QuestionController::class, 'unanswered'])->name('unanswered');
        Route::get('popular', [QuestionController::class, 'popular'])->name('popular');
    });

    // Milestone
    Route::group(['prefix' => 'milestones', 'as' => 'milestones.'], function () {
        Route::get('', [MilestoneController::class, 'opened'])->name('opened');
        Route::get('closed', [MilestoneController::class, 'closed'])->name('closed');
        Route::get('{id}', [MilestoneController::class, 'milestone'])->name('milestone');
    });

    // Search
    Route::group(['prefix' => 'search', 'as' => 'search.'], function () {
        Route::get('', [SearchController::class, 'search'])->name('home');
        Route::get('tasks', [SearchController::class, 'tasks'])->name('tasks');
        Route::get('comments', [SearchController::class, 'comments'])->name('comments');
        Route::get('questions', [SearchController::class, 'questions'])->name('questions');
        Route::get('answers', [SearchController::class, 'answers'])->name('answers');
        Route::get('products', [SearchController::class, 'products'])->name('products');
        Route::get('users', [SearchController::class, 'users'])->name('users');
    });

    // Admin
    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['staff']], function () {
        Route::view('users', 'admin.users')->middleware('password.confirm')->name('users');
        Route::view('tasks', 'admin.tasks')->middleware('password.confirm')->name('tasks');
        Route::view('activities', 'admin.activities')->middleware('password.confirm')->name('activities');
        Route::view('products', 'admin.products')->middleware('password.confirm')->name('products');
        Route::get('adminbar', [AdminController::class, 'toggle'])->name('adminbar');
    });

    // Patron
    Route::group(['prefix' => 'patron', 'as' => 'patron.'], function () {
        Route::view('', 'pages.patron')->name('home');
    });

    // Paddle Integration
    Route::post('paddle/webhook', [PatronController::class, 'handleWebhook'])->name('paddle.webhook');

    // Dark mode
    Route::get('darkmode', [UserController::class, 'darkMode'])->name('darkmode')->middleware('patron');

    // Single Task and comment
    Route::group(['prefix' => 'task'], function () {
        Route::get('{id}', [TaskController::class, 'task'])->name('task');
        Route::get('{id}/{comment_id}', [TaskController::class, 'comment'])->name('comment');
    });

    // Zen mode tasks
    Route::view('tasks', 'tasks.tasks')->name('tasks')->middleware('auth');

    // Pages
    Route::view('about', 'pages.about')->name('about');
    Route::view('terms', 'pages.terms')->name('terms');
    Route::view('privacy', 'pages.privacy')->name('privacy');
    Route::view('security', 'pages.security')->name('security');
    Route::view('sponsors', 'pages.sponsors')->name('sponsors');
    Route::view('contact', 'pages.contact')->name('contact');
    Route::view('reputation', 'pages.reputation')->name('reputation')->middleware('auth');
    Route::view('open', 'pages.open')->name('open');
    Route::get('deals', [PagesController::class, 'deals'])->name('deals');

    // Meetups
    Route::group(['prefix' => 'meetups', 'as' => 'meetups.'], function () {
        Route::get('/', [MeetupController::class, 'meetups'])->name('home')->middleware('staff');
        Route::get('/rsvpd', [MeetupController::class, 'rsvpd'])->name('rsvpd')->middleware('staff');
        Route::get('/finished', [MeetupController::class, 'finished'])->name('finished')->middleware('staff');
    });

    // https://web.dev/change-password-url
    Route::get('.well-known/change-password', function () {
        return redirect()->route('user.settings.password');
    });

    // Sitemaps
    Route::get('sitemap_users.txt', [SitemapController::class, 'users']);
    Route::get('sitemap_products.txt', [SitemapController::class, 'products']);
    Route::get('sitemap_questions.txt', [SitemapController::class, 'questions']);
    Route::get('sitemap_tasks.txt', [SitemapController::class, 'tasks']);
    Route::get('sitemap_comments.txt', [SitemapController::class, 'comments']);
    Route::view('sitemap_urls.txt', 'seo.sitemap_urls');

    // Status

resources/views/pages/about.blade.php
@extends('layouts.app')

@section('pageTitle', 'About ·')
@section('title', 'About ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
<div class="container-md">
    <div class="card">
        <div class="card-header pt-3 pb-3">
            <span class="h5">Heading</span>
            <div>Sub-heading</div>
        </div>
        <div class="card-body">
            Soon
        </div>
    </div>
</div>
@endsection

resources/views/pages/contact.blade.php
@extends('layouts.app')

@section('pageTitle', 'Contact ·')
@section('title', 'Contact ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
<div class="container-md">
<div class="row justify-content-center" style="height:70vh">
    <div class="col-lg-7 mt-5">
        @auth
        @php
        $username = "@".auth()->user()->username;
        $email = urlencode(auth()->user()->email);
        $url = "https://tally.so/embed/5mVVam?username=".$username."&email=".$email."&transparentBackground=1";
        @endphp
        <iframe
            src="{{$url}}"
            width="100%"
            height="100%"
            frameborder="0"
            marginheight="0"
            marginwidth="0"
        ></iframe>
        @else
        <iframe
            src="https://tally.so/embed/63lL53?transparentBackground=1"
            width="100%"
            height="100%"
            frameborder="0"
            marginheight="0"
            marginwidth="0"
        ></iframe>
        @endauth
    </div>
</div>
</div>
@endsection

resources/views/pages/deals.blade.php
@extends('layouts.app')

@section('pageTitle', 'Deals ·')
@section('title', 'Deals ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
<div class="container-md">
    <div class="card">
        <div class="card-header pt-3 pb-3">
            <span class="h5">Deals</span>
            <div>Discounts and special deals for Taskord members. Only available for patrons.</div>
            <div>
                <a href="https://tally.so/r/63l4o3" target="_blank" rel="noreferrer">Add your product</a>
            </div>
            @auth
            @if (auth()->user()->staffShip)
            <button type="button" class="mt-2 btn btn-success text-white" data-bs-toggle="modal" data-bs-target="#newQuestionModal">
                <x-heroicon-o-plus class="heroicon" />
                Add a Deal
            </button>
            @livewire('pages.create-deal')
            @endif
            @endauth
        </div>
        <div class="card-body">
            @if (count($deals) === 0)
            <div class="card-body text-center mt-3 mb-3">
                <x-heroicon-o-gift class="heroicon-4x text-primary mb-2" />
                <div class="h4">
                    No deals found
                </div>
            </div>
            @endif
            @foreach ($deals as $deal)
                <div class="d-flex align-items-center {{ $loop->last ? '' : 'mb-5' }}">
                    <div>
                        <img loading=lazy class="rounded avatar-100" src="{{ $deal->logo }}" height="100" width="100" alt="{{ $deal->name }}'s Logo" />
                    </div>
                    <div class="ms-4">
                        <span class="h4">
                            {{ $deal->name }}
                        </span>
                        <span class="h5">
                            <span class="align-text-top badge bg-success ms-1">{{ $deal->offer }}% OFF</span>
                        </span>
                        <div class="h6 mt-3">{{ $deal->description }}</div>
                        <div class="mt-2">
                            <a href="{{ $deal->website }}" target="_blank">{{ $deal->website }}</a>
                        </div>
                        @auth
                        @if (auth()->user()->isPatron)
                        @if ($deal->coupon)
                        <div class="mt-2">
                            Coupon Code
                            <code class="ms-2 fw-bold">
                                {{ $deal->coupon }}
                            </code>
                        </div>
                        @else
                        <div class="mt-2 fw-bold">
                            <a href="{{ $deal->referral }}" target="_blank">
                                Click here to get your deal
                            </a>
                        </div>
                        @endif
                        @else
                        <div class="mt-2">
                            <a class="text-secondary" href="{{ route('patron.home') }}">You must be a patron to see coupon code.</a>
                        </div>
                        @endif
                        @endauth
                        @guest
                        <div class="mt-2">
                            <a class="text-secondary" href="{{ route('login') }}">Login to view coupon code.</a>
                        </div>
                        @endguest
                        @auth
                        @endauth
                    </div>
                </div>
            @endforeach
        </div>
    </div>
</div>
@endsection

resources/views/pages/open.blade.php
@extends('layouts.app')

@section('pageTitle', 'Open ·')
@section('title', 'Open ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
<div class="container-md">
    <div class="card">
        <div class="card-header pt-3 pb-3">
            <span class="h5">Open</span>
            <div>Analytics of Taskord</div>
        </div>
        <div class="card-body">
            @livewire('pages.open.all-tasks')
            @livewire('pages.open.completed-tasks')
            @livewire('pages.open.reputations')
        </div>
    </div>
</div>
@endsection

resources/views/pages/patron.blade.php
@extends('layouts.app')

@section('pageTitle', 'Patron ·')
@section('title', 'Patron ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
<div class="container-md">
    <div class="mb-4 text-center">
        <img loading=lazy src="/images/patron.svg" width="100" />
    </div>
    <div class="card">
        <div class="card-header pt-3 pb-3">
            <span class="h5">Become a Patron</span>
            <div>Support Taskord by becoming a Patron.</div>
        </div>
        <div class="card-body">
            <div class="row align-items-center font-monospace">
                <div class="col-lg-8">
                    <div class="fw-bold mb-3">You get the following benefits</div>
                    <ul>
                        <li>🌑 Enable Awesome Dark Mode</li>
                        <li>💬 Patrons only discussion to make it more meaningful</li>
                        <li>🔒 Make your tasks private and get personal things done</li>
                        <li>🤝 Show off your support with the Patron badge</li>
                        <li>👍 Fund on-going development of the platform and server fee</li>
                        <li>More coming soon...</li>
                    </ul>
                </div>
                <div class="col-sm d-grid">
                    @auth
                    @if (auth()->user()->isPatron and auth()->user()->patron()->count('id') === 1)
                    <div class="text-center">
                        <div class="h5">
                            ❤ You are already a patron!
                        </div>
                        <a class="text-primary" href="{{ route('user.settings.patron') }}">
                            Go to settings
                        </a>
                    </div>
                    @else
                    <a
                        class="paddle_button btn btn-primary"
                        data-theme="none"
                        data-product="619848"
                        data-message="Support $5/month for Taskord!"
                        data-email="{{ auth()->user()->email }}"
                    >
                        Support $5/month
                    </a>
                    <a
                        class="paddle_button btn mt-2 btn-primary"
                        data-theme="none"
                        data-product="621377"
                        data-message="Support $10/month for Taskord!"
                        data-email="{{ auth()->user()->email }}"
                    >
                        Support $10/month
                    </a>
                    <a
                        class="paddle_button btn mt-2 btn-primary"
                        data-theme="none"
                        data-product="621379"
                        data-message="Support $20/month for Taskord!"
                        data-email="{{ auth()->user()->email }}"
                    >
                        Support $20/month
                    </a>
                    <a
                        class="paddle_button btn mt-2 btn-primary"
                        data-theme="none"
                        data-product="621380"
                        data-message="Support $50/month for Taskord!"
                        data-email="{{ auth()->user()->email }}"
                    >
                        Support $50/month
                    </a>
                    <a
                        class="paddle_button btn mt-2 btn-primary"
                        data-theme="none"
                        data-product="629491"
                        data-message="Support $100 onetime for lifetime pro in Taskord!"
                        data-email="{{ auth()->user()->email }}"
                    >
                        Support $100 onetime
                    </a>
                    @endif
                    @endauth
                    @guest
                    <a class="btn mt-2 btn-success text-white" href="{{ route('login') }}">
                        Login to support!
                    </a>
                    @endguest
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://cdn.paddle.com/paddle/paddle.js"></script>
<script type="text/javascript">
	Paddle.Setup({ vendor: 120187 });
</script>
@endsection

resources/views/pages/privacy.blade.php
@extends('layouts.app')

@section('pageTitle', 'Privacy ·')
@section('title', 'Privacy ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
<div class="container-md">
    <div class="card">
        <div class="card-header pt-3 pb-3">
            <span class="h5">Privacy Policy</span>
            <div>Web Site Privacy Policy</div>
        </div>
        <div class="card-body">
            <div>
                Taskord built the Taskord app as an Open Source app. This SERVICE is provided by Taskord at no cost and is intended for use as is.
            </div>
            <div>
                This page is used to inform visitors regarding my policies with the collection, use, and disclosure of Personal Information if anyone decided to use my Service.
            </div>
            <div>
                If you choose to use my Service, then you agree to the collection and use of information in relation to this policy. The Personal Information that I collect is used for providing and improving the Service. I will not use or share your information with anyone except as described in this Privacy Policy.
            </div>
            <div>
                The terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, which is accessible at Taskord unless otherwise defined in this Privacy Policy.
            </div>
            <h5 class="mt-4">Information Collection and Use</h5>
            <div>
                For a better experience, while using our Service, I may require you to provide us with certain personally identifiable information. The information that I request will be retained on your device and is not collected by me in any way.
            </div>
            <h5 class="mt-4">Log Data</h5>
            <div>
                I want to inform you that whenever you use my Service, in a case of an error in the app I collect data and information (through third party products) on your phone called Log Data. This Log Data may include information such as your device Internet Protocol (“IP”) address, device name, operating system version, the configuration of the app when utilizing my Service, the time and date of your use of the Service, and other statistics.
            </div>
            <h5 class="mt-4">Cookies</h5>
            <div>
                Cookies are files with a small amount of data that are commonly used as anonymous unique identifiers. These are sent to your browser from the websites that you visit and are stored on your device's internal memory.
            </div>
            <div>
                This Service does not use these “cookies” explicitly. However, the app may use third party code and libraries that use “cookies” to collect information and improve their services. You have the option to either accept or refuse these cookies and know when a cookie is being sent to your device. If you choose to refuse our cookies, you may not be able to use some portions of this Service.
            </div>
            <h5 class="mt-4">Service Providers</h5>
            <div>
                I may employ third-party companies and individuals due to the following reasons:
            </div>
            <div class="mt-3">
                <ul>
                    <li>To facilitate our Service;</li>
                    <li>To provide the Service on our behalf;</li>
                    <li>To perform Service-related services; or</li>
                    <li>To assist us in analyzing how our Service is used.</li>
                </ul>
            </div>
            <div>
                I want to inform users of this Service that these third parties have access to your Personal Information. The reason is to perform the tasks assigned to them on our behalf. However, they are obligated not to disclose or use the information for any other purpose.
            </div>
            <h5 class="mt-4">Security</h5>
            <div>
                I value your trust in providing us your Personal Information, thus we are striving to use commercially acceptable means of protecting it. But remember that no method of transmission over the internet, or method of electronic storage is 100% secure and reliable, and I cannot guarantee its absolute security.
            </div>
            <h5 class="mt-4">Links to Other Sites</h5>
            <div>
                This Service may contain links to other sites. If you click on a third-party link, you will be directed to that site. Note that these external sites are not operated by me. Therefore, I strongly advise you to review the Privacy Policy of these websites. I have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.
            </div>
            <h5 class="mt-4">Children’s Privacy</h5>
            <div>
                These Services do not address anyone under the age of 13. I do not knowingly collect personally identifiable information from children under 13. In the case I discover that a child under 13 has provided me with personal information, I immediately delete this from our servers. If you are a parent or guardian and you are aware that your child has provided us with personal information, please contact me so that I will be able to do necessary actions.
            </div>
            <h5 class="mt-4">Changes to This Privacy Policy</h5>
            <div>
                I may update our Privacy Policy from time to time. Thus, you are advised to review this page periodically for any changes. I will notify you of any changes by posting the new Privacy Policy on this page.
            </div>
            <div>
                This policy is effective as of 2020-09-10
            </div>
            <h5 class="mt-4">Contact Us</h5>
            <div>
                If you have any questions or suggestions about my Privacy Policy, do not hesitate to contact me at yo@taskord.com.
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/reputation.blade.php
@extends('layouts.app')

@section('pageTitle', 'Reputation ·')
@section('title', 'Reputation ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
<div class="container-md">
    <div class="row justify-content-center mt-4">
        <div class="col-sm">
            <div class="card mb-4">
            <div class="card-header pt-3 pb-3">
                <span class="h5 text-success">Badges</span>
            </div>
            <div class="card-body">
                <div class="d-flex justify-content-between">
                    <span class="fw-bold">Beginner</span>
                    <span>0 to 500</span>
                </div>
                <div class="d-flex justify-content-between mt-2">
                    <span class="fw-bold">Novice</span>
                    <span>500 to 2500</span>
                </div>
                <div class="d-flex justify-content-between mt-2">
                    <span class="fw-bold">Intermediate</span>
                    <span>2500 to 5000</span>
                </div>
                <div class="d-flex justify-content-between mt-2">
                    <span class="fw-bold">Professional</span>
                    <span>5000 to 7500</span>
                </div>
                <div class="d-flex justify-content-between mt-2">
                    <span class="fw-bold">Expert</span>
                    <span>7500 to 10000</span>
                </div>
                <div class="d-flex justify-content-between mt-2">
                    <span class="fw-bold">Master</span>
                    <span>10000 to 20000</span>
                </div>
                <div class="d-flex justify-content-between mt-2">
                    <span class="fw-bold">GrandMaster</span>
                    <span>20000 to 50000</span>
                </div>
                <div class="d-flex justify-content-between mt-2">
                    <span class="fw-bold">Enlightened</span>
                    <span>50000 and above</span>
                </div>
            </div>
            </div>
        </div>
        <div class="col-lg-8">
            @livewire('user.reputations')
        </div>
    </div>
</div>
@endsection